---
# Staging environment secrets -- encrypt values with: ansible-vault encrypt_string 'value' --name 'var_name'

# aap_pass: !vault |
#           $ANSIBLE_VAULT;1.1;AES256
#           ...your encrypted string...

# ldap_bind_password: !vault |
#           $ANSIBLE_VAULT;1.1;AES256
#           ...your encrypted string...

# github_username: !vault |
#           $ANSIBLE_VAULT;1.1;AES256
#           ...your encrypted string...

# github_token: !vault |
#           $ANSIBLE_VAULT;1.1;AES256
#           ...your encrypted string...

# redhat_api_token: !vault |
#           $ANSIBLE_VAULT;1.1;AES256
#           ...your encrypted string...
...
