---
all:
  children:
    dev:
      hosts:
        localhost:
  vars:
    env: dev
    aap_hostname: "https://aap-aap27.apps-crc.testing"
    aap_username: "{{ aap_user | default('admin') }}"
    aap_password: "{{ aap_pass }}"
    aap_validate_certs: false
...
