---
# Dev environment secrets
# Encrypt values with: ansible-vault encrypt_string 'value' --name 'var_name'

# aap_pass: !vault |
#           $ANSIBLE_VAULT;1.1;AES256
#           ...your encrypted string...
...
